version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test

workflows:
  sample:
    jobs:
      - build-and-test
      - heroku/deploy-  via-git: # Use the pre-configured job, deploy-via-git
          api-key: '21edda20-257e-42bb-a721-c8eb350e17be' 
          app-name: lendcubev2 
          branch: main 
          requires:
            - build-and-test
          filters:
            branches:
              only: main